### ISSUE TITLE
Issue with windows

### ISSUE THREAD

**Issue by vaweto** [hardpixel/marv#29]
1) Installing on windows 7 i can not install additional dependencies. Command 'install build-essential mysql-server mysql-client libmysqlclient-dev php5-cli php5-mysql ' is not recognized by the syste.

2)Failed to build gem native extensio, error installing marv

**Comment by jonian** [comment]
The command 'install build-essential mysql-server mysql-client libmysqlclient-dev php5-cli php5-mysql ' is only for linux systems.

In windows you have to install PHP and MySQL manually along with the development modules, so you can build the gem with native extensions.

Also try recommendations in this issue on windows
https://github.com/rubygems/rubygems/issues/977
